[2021-04-12T01:57:40.628+08:00] [INFO] [Thread-0-14] [com.newbiegroup.hermes.rpc.RpcServer] [RpcServer.java,78,com.newbiegroup.hermes.rpc.RpcServer,start] [start hermes rpc channel success!] ## ''
[2021-04-12T01:57:40.628+08:00] [INFO] [nioEventLoopGroup-2-1-20] [com.newbiegroup.hermes.rpc.RpcServer] [RpcServer.java,67,com.newbiegroup.hermes.rpc.RpcServer$2,operationComplete] [server success bind to 127.0.0.1:8765] ## ''
[2021-04-12T02:00:26.072+08:00] [ERROR] [nioEventLoopGroup-3-1-21] [com.newbiegroup.hermes.rpc.RpcServerHandler] [RpcServerHandler.java,100,com.newbiegroup.hermes.rpc.RpcServerHandler,exceptionCaught] [server caught throwable:java.io.IOException: 远程主机强迫关闭了一个现有的连接。] ## ''
[2021-04-12T02:00:42.118+08:00] [ERROR] [nioEventLoopGroup-3-2-22] [com.newbiegroup.hermes.rpc.RpcServerHandler] [RpcServerHandler.java,100,com.newbiegroup.hermes.rpc.RpcServerHandler,exceptionCaught] [server caught throwable:java.io.IOException: 远程主机强迫关闭了一个现有的连接。] ## ''
[2021-04-12T02:01:13.136+08:00] [ERROR] [nioEventLoopGroup-3-3-23] [com.newbiegroup.hermes.rpc.RpcServerHandler] [RpcServerHandler.java,100,com.newbiegroup.hermes.rpc.RpcServerHandler,exceptionCaught] [server caught throwable:java.io.IOException: 远程主机强迫关闭了一个现有的连接。] ## ''
rrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:570)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:549)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)
	at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:604)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
	at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:300)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:335)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:702)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
'
[2021-04-12T02:00:31.480+08:00] [WARN] [nioEventLoopGroup-3-1-19] [io.netty.util.concurrent.DefaultPromise] [DefaultPromise.java,580,io.netty.util.concurrent.DefaultPromise,notifyListener0] [An exception was thrown by com.newbiegroup.rpc.remoting.client.RpcConnectManager$3.operationComplete()] ## ' java.lang.NullPointerException
	at java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011)
	at java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006)
	at com.newbiegroup.rpc.remoting.client.RpcConnectManager.addHandler(RpcConnectManager.java:202)
	at com.newbiegroup.rpc.remoting.client.RpcConnectManager.access$300(RpcConnectManager.java:39)
	at com.newbiegroup.rpc.remoting.client.RpcConnectManager$3.operationComplete(RpcConnectManager.java:187)
	at com.newbiegroup.rpc.remoting.client.RpcConnectManager$3.operationComplete(RpcConnectManager.java:182)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:570)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:549)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)
	at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:604)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
	at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:300)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:335)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:702)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
'
[2021-04-12T02:01:12.755+08:00] [WARN] [nioEventLoopGroup-3-1-19] [io.netty.util.concurrent.DefaultPromise] [DefaultPromise.java,580,io.netty.util.concurrent.DefaultPromise,notifyListener0] [An exception was thrown by com.newbiegroup.rpc.remoting.client.RpcConnectManager$3.operationComplete()] ## ' java.lang.NullPointerException
	at java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011)
	at java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006)
	at com.newbiegroup.rpc.remoting.client.RpcConnectManager.addHandler(RpcConnectManager.java:202)
	at com.newbiegroup.rpc.remoting.client.RpcConnectManager.access$300(RpcConnectManager.java:39)
	at com.newbiegroup.rpc.remoting.client.RpcConnectManager$3.operationComplete(RpcConnectManager.java:187)
	at com.newbiegroup.rpc.remoting.client.RpcConnectManager$3.operationComplete(RpcConnectManager.java:182)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:570)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:549)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)
	at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:604)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
	at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:300)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:335)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:702)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
'
[2021-04-12T02:04:10.716+08:00] [INFO] [nioEventLoopGroup-2-1-20] [com.newbiegroup.hermes.rpc.RpcServer] [RpcServer.java,67,com.newbiegroup.hermes.rpc.RpcServer$2,operationComplete] [server success bind to 127.0.0.1:8765] ## ''
[2021-04-12T02:04:10.716+08:00] [INFO] [Thread-0-14] [com.newbiegroup.hermes.rpc.RpcServer] [RpcServer.java,78,com.newbiegroup.hermes.rpc.RpcServer,start] [start hermes rpc channel success!] ## ''
[2021-04-12T02:04:53.239+08:00] [ERROR] [nioEventLoopGroup-3-1-21] [com.newbiegroup.hermes.rpc.RpcServerHandler] [RpcServerHandler.java,100,com.newbiegroup.hermes.rpc.RpcServerHandler,exceptionCaught] [server caught throwable:java.io.IOException: 远程主机强迫关闭了一个现有的连接。] ## ''
[2021-04-12T02:06:04.324+08:00] [ERROR] [nioEventLoopGroup-3-2-22] [com.newbiegroup.hermes.rpc.RpcServerHandler] [RpcServerHandler.java,100,com.newbiegroup.hermes.rpc.RpcServerHandler,exceptionCaught] [server caught throwable:java.io.IOException: 远程主机强迫关闭了一个现有的连接。] ## ''
oting.client.RpcConnectManager.access$300(RpcConnectManager.java:39)
	at com.newbiegroup.rpc.remoting.client.RpcConnectManager$3.operationComplete(RpcConnectManager.java:187)
	at com.newbiegroup.rpc.remoting.client.RpcConnectManager$3.operationComplete(RpcConnectManager.java:182)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:570)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:549)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)
	at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:604)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
	at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:300)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:335)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:702)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
'
[2021-04-12T02:05:53.292+08:00] [WARN] [nioEventLoopGroup-2-1-19] [io.netty.util.concurrent.DefaultPromise] [DefaultPromise.java,580,io.netty.util.concurrent.DefaultPromise,notifyListener0] [An exception was thrown by com.newbiegroup.rpc.remoting.client.RpcConnectManager$3.operationComplete()] ## ' java.lang.NullPointerException
	at java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011)
	at java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006)
	at com.newbiegroup.rpc.remoting.client.RpcConnectManager.addHandler(RpcConnectManager.java:202)
	at com.newbiegroup.rpc.remoting.client.RpcConnectManager.access$300(RpcConnectManager.java:39)
	at com.newbiegroup.rpc.remoting.client.RpcConnectManager$3.operationComplete(RpcConnectManager.java:187)
	at com.newbiegroup.rpc.remoting.client.RpcConnectManager$3.operationComplete(RpcConnectManager.java:182)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:570)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:549)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)
	at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:604)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
	at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:300)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:335)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:702)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
'
[2021-04-12T02:09:19.444+08:00] [INFO] [Thread-0-14] [com.newbiegroup.hermes.rpc.RpcServer] [RpcServer.java,78,com.newbiegroup.hermes.rpc.RpcServer,start] [start hermes rpc channel success!] ## ''
[2021-04-12T02:09:19.444+08:00] [INFO] [nioEventLoopGroup-2-1-20] [com.newbiegroup.hermes.rpc.RpcServer] [RpcServer.java,67,com.newbiegroup.hermes.rpc.RpcServer$2,operationComplete] [server success bind to 127.0.0.1:8765] ## ''
[2021-04-12T02:11:27.519+08:00] [ERROR] [nioEventLoopGroup-3-1-21] [com.newbiegroup.hermes.rpc.RpcServerHandler] [RpcServerHandler.java,100,com.newbiegroup.hermes.rpc.RpcServerHandler,exceptionCaught] [server caught throwable:java.io.IOException: 远程主机强迫关闭了一个现有的连接。] ## ''
ng.NullPointerException
	at java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011)
	at java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006)
	at com.newbiegroup.rpc.remoting.client.RpcConnectManager.addHandler(RpcConnectManager.java:202)
	at com.newbiegroup.rpc.remoting.client.RpcConnectManager.access$300(RpcConnectManager.java:39)
	at com.newbiegroup.rpc.remoting.client.RpcConnectManager$3.operationComplete(RpcConnectManager.java:187)
	at com.newbiegroup.rpc.remoting.client.RpcConnectManager$3.operationComplete(RpcConnectManager.java:182)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:570)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:549)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)
	at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:604)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
	at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:300)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:335)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:702)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
'
[2021-04-12T02:11:40.438+08:00] [WARN] [nioEventLoopGroup-2-1-19] [io.netty.util.concurrent.DefaultPromise] [DefaultPromise.java,580,io.netty.util.concurrent.DefaultPromise,notifyListener0] [An exception was thrown by com.newbiegroup.rpc.remoting.client.RpcConnectManager$3.operationComplete()] ## ' java.lang.NullPointerException
	at java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011)
	at java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006)
	at com.newbiegroup.rpc.remoting.client.RpcConnectManager.addHandler(RpcConnectManager.java:202)
	at com.newbiegroup.rpc.remoting.client.RpcConnectManager.access$300(RpcConnectManager.java:39)
	at com.newbiegroup.rpc.remoting.client.RpcConnectManager$3.operationComplete(RpcConnectManager.java:187)
	at com.newbiegroup.rpc.remoting.client.RpcConnectManager$3.operationComplete(RpcConnectManager.java:182)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:570)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:549)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)
	at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:604)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
	at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:300)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:335)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:702)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
'
[2021-04-12T16:35:03.516+08:00] [INFO] [Thread-0-14] [com.newbiegroup.hermes.rpc.RpcServer] [RpcServer.java,78,com.newbiegroup.hermes.rpc.RpcServer,start] [start hermes rpc channel success!] ## ''
[2021-04-12T16:35:03.516+08:00] [INFO] [nioEventLoopGroup-2-1-20] [com.newbiegroup.hermes.rpc.RpcServer] [RpcServer.java,67,com.newbiegroup.hermes.rpc.RpcServer$2,operationComplete] [server success bind to 127.0.0.1:8765] ## ''
[2021-04-12T16:50:29.019+08:00] [WARN] [nioEventLoopGroup-2-1-19] [io.netty.util.concurrent.DefaultPromise] [DefaultPromise.java,580,io.netty.util.concurrent.DefaultPromise,notifyListener0] [An exception was thrown by com.newbiegroup.rpc.remoting.client.RpcConnectManager$3.operationComplete()] ## ' java.lang.NullPointerException
	at java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011)
	at java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006)
	at com.newbiegroup.rpc.remoting.client.RpcConnectManager.addHandler(RpcConnectManager.java:202)
	at com.newbiegroup.rpc.remoting.client.RpcConnectManager.access$300(RpcConnectManager.java:39)
	at com.newbiegroup.rpc.remoting.client.RpcConnectManager$3.operationComplete(RpcConnectManager.java:187)
	at com.newbiegroup.rpc.remoting.client.RpcConnectManager$3.operationComplete(RpcConnectManager.java:182)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:570)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:549)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)
	at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:604)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
	at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:300)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:335)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:702)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
'
[2021-04-12T16:52:36.084+08:00] [INFO] [Thread-0-14] [com.newbiegroup.hermes.rpc.RpcServer] [RpcServer.java,78,com.newbiegroup.hermes.rpc.RpcServer,start] [start hermes rpc channel success!] ## ''
[2021-04-12T16:52:36.084+08:00] [INFO] [nioEventLoopGroup-2-1-20] [com.newbiegroup.hermes.rpc.RpcServer] [RpcServer.java,67,com.newbiegroup.hermes.rpc.RpcServer$2,operationComplete] [server success bind to 127.0.0.1:8765] ## ''
[2021-04-12T16:53:37.950+08:00] [ERROR] [nioEventLoopGroup-3-1-21] [com.newbiegroup.hermes.rpc.RpcServerHandler] [RpcServerHandler.java,100,com.newbiegroup.hermes.rpc.RpcServerHandler,exceptionCaught] [server caught throwable:java.io.IOException: 远程主机强迫关闭了一个现有的连接。] ## ''
[2021-04-12T16:54:05.541+08:00] [ERROR] [nioEventLoopGroup-3-2-22] [com.newbiegroup.hermes.rpc.RpcServerHandler] [RpcServerHandler.java,100,com.newbiegroup.hermes.rpc.RpcServerHandler,exceptionCaught] [server caught throwable:java.io.IOException: 远程主机强迫关闭了一个现有的连接。] ## ''
[2021-04-12T16:55:20.343+08:00] [ERROR] [nioEventLoopGroup-3-3-24] [com.newbiegroup.hermes.rpc.RpcServerHandler] [RpcServerHandler.java,100,com.newbiegroup.hermes.rpc.RpcServerHandler,exceptionCaught] [server caught throwable:java.io.IOException: 远程主机强迫关闭了一个现有的连接。] ## ''
[2021-04-12T16:55:32.224+08:00] [ERROR] [pool-5-thread-1-26] [com.newbiegroup.hermes.rpc.RpcServerHandler] [RpcServerHandler.java,55,com.newbiegroup.hermes.rpc.RpcServerHandler$1,run] [rpc server handle request throwable:java.lang.NullPointerException] ## ''
util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)
	at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:604)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
	at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:300)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:335)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:702)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
'
[2021-04-12T16:56:50.951+08:00] [INFO] [nioEventLoopGroup-2-1-20] [com.newbiegroup.hermes.rpc.RpcServer] [RpcServer.java,67,com.newbiegroup.hermes.rpc.RpcServer$2,operationComplete] [server success bind to 127.0.0.1:8765] ## ''
[2021-04-12T16:56:50.951+08:00] [INFO] [Thread-0-14] [com.newbiegroup.hermes.rpc.RpcServer] [RpcServer.java,78,com.newbiegroup.hermes.rpc.RpcServer,start] [start hermes rpc channel success!] ## ''
[2021-04-12T16:57:14.476+08:00] [ERROR] [pool-2-thread-1-22] [com.newbiegroup.hermes.rpc.RpcServerHandler] [RpcServerHandler.java,55,com.newbiegroup.hermes.rpc.RpcServerHandler$1,run] [rpc server handle request throwable:java.lang.NullPointerException] ## ''
[2021-04-12T17:50:45.026+08:00] [ERROR] [nioEventLoopGroup-3-1-21] [com.newbiegroup.hermes.rpc.RpcServerHandler] [RpcServerHandler.java,100,com.newbiegroup.hermes.rpc.RpcServerHandler,exceptionCaught] [server caught throwable:java.io.IOException: 远程主机强迫关闭了一个现有的连接。] ## ''
[2021-04-12T17:50:56.448+08:00] [INFO] [nioEventLoopGroup-2-1-20] [com.newbiegroup.hermes.rpc.RpcServer] [RpcServer.java,67,com.newbiegroup.hermes.rpc.RpcServer$2,operationComplete] [server success bind to 127.0.0.1:8765] ## ''
[2021-04-12T17:50:56.448+08:00] [INFO] [Thread-0-14] [com.newbiegroup.hermes.rpc.RpcServer] [RpcServer.java,78,com.newbiegroup.hermes.rpc.RpcServer,start] [start hermes rpc channel success!] ## ''
[2021-04-12T17:56:35.065+08:00] [INFO] [Thread-0-14] [com.newbiegroup.hermes.rpc.RpcServer] [RpcServer.java,78,com.newbiegroup.hermes.rpc.RpcServer,start] [start hermes rpc channel success!] ## ''
[2021-04-12T17:56:35.065+08:00] [INFO] [nioEventLoopGroup-2-1-20] [com.newbiegroup.hermes.rpc.RpcServer] [RpcServer.java,67,com.newbiegroup.hermes.rpc.RpcServer$2,operationComplete] [server success bind to 127.0.0.1:8765] ## ''
